const coeffsTemplateAttack = [new Stat(1.30, 'speed'), 
new Stat(1.20, 'attackPercent'),
new Stat(1.10, 'criRate'),
new Stat(1.10, 'criDamage'),
new Stat(1.10, 'attackFlat'),
new Stat(0.90, 'defense'),
new Stat(1, 'resistance'),
new Stat(1, 'accuracy'),
new Stat(1, 'hpFlat'),
new Stat(1, 'attackFlat'),
new Stat(1, 'defenseFlat')]